### ISSUE TITLE
Stuck on 75% on Executing on Run

### ISSUE THREAD

**Issue by CheckeredZer0** [ksandom/handWavey#35]
![image](https://github.com/ksandom/handWavey/assets/144742540/f5b14434-0943-4e3b-958d-d99bfbd42132)

**Comment by CheckeredZer0** [comment]
Running on windows 11 with the leap motion controller 2

**Comment by ksandom** [comment]
Hey hey. Sorry for the slow response.

I see that you've closed the issue. Did you solve it?

It looks to me like handWavey is not able to see the device. These are the possibilities I can think of:

* Did you have success with the "Copy libraries from the LeapMotion SDK to lib." step when running it? I think I need to improve the documentation around this. I'll look at this in the coming week.
* Is the Leap motion controller working with other apps?
    * What version of the libraries are you using? SDK 2.3.1 is known to work.
* I don't know if the leap motion controller 2 will work with SDK 2.3.1. If you get it working, please let me know.
* I don't know if handWavey will be able to work with newer versions of the SDK. If you get it working, please let me know.

You can safely ignore the 75%. That's a quirk of how I'm running it. Pull-requests welcome.
